django_demo/urls.py
from django.contrib import admin
from django.urls import path, include
from learn import views as learn_views
from rent_proj import views as rent_views

urlpatterns = [
    path('mpa/', include('mpa.urls')),
    path('rent/', rent_views.index),
    path('', learn_views.index),
    path('add/', learn_views.add),
    path('add/<int:a>/<int:b>/', learn_views.add2),
    path('new_add/<int:a>/<int:b>/', learn_views.add2),
    path('admin/', admin.site.urls),
]

mpa/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from rest_framework.routers import DefaultRouter
from mpa.user.UserView import UserViewSet

router = DefaultRouter()
router.register('user', UserViewSet)

app_name = 'mpa'

urlpatterns = [
    path('', views.home, name='home1'),
    path('home/', views.home, name='home'),
    path('demos/<str:a>/<str:b>', views.demos, name='demo'),
    # path('elements/<str:a>/', mpam_views.elements),
    # path('components/<str:a>/', mpam_views.components),
    # path('tables/<str:a>/', mpam_views.tables),
    # path('charts/<str:a>/', mpam_views.charts),
    #path('to_register/', views.to_register, name='to_register'),
    #path('to_reset_pw/', views.to_reset_pw, name='to_reset_pw'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('reset_pw/', views.reset_pw, name='reset_pw'),
    path('index/', views.index, name='index')
]

learn/models.py
from django.db import models

# Create your models here.

mpa/models.py
from django.db import models
import pickle as p
from rest_framework import serializers

class SerializedField(serializers.ModelSerializer):
    """
    使用pickle来实现存储 Python 对象
    """
    __metaclass__ = models



# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)
    email = models.CharField(max_length=100, null=True)
    password = models.TextField(max_length=50)
    create_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

rent_proj/models.py
from django.db import models

# Create your models here.

learn/views.py
# coding:utf-8
from django.http import response
from django.shortcuts import render

# Create your views here.
def index(request):
    #return response.HttpResponse(u'次茶杯差别万磁王')
    return render(request, 'learn/home.html')

def add(request):
    a = request.GET.get('a', 0)
    b = request.GET.get('b', 0)
    c = int(a) + int(b)
    return response.HttpResponse(c)

def add2(request, a=0, b=0):
    c = int(a) + int(b)
    return response.HttpResponse(c)

#def old_add2_redirect(request, a, b):
#    response.HttpResponseRedirect()

mpa/views.py
# coding:utf-8
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import User


# Create your views here.
def login(request):
    if request.method == 'POST':
        user_name = request.POST.get('user_name')
        password = request.POST.get('password')
        remember_me = request.POST.get('remember_me')  # ON None
        # user = get_object_or_404(User, name=user_name)
        user = User.objects.get(name=user_name)
        if user is None:
            raise User.DoesNotExist()
        else:
            return render(request, 'mpa/home.html')
    else:
        return render(request, 'mpa/login.html')


def register(request):
    if request.method == 'POST':
        user_name = request.POST.get('user_name')
        password = request.POST.get('password')
        user = User()
        user.name = user_name
        User.objects.create()
    else:
        return render(request, 'mpa/register.html')


def reset_pw(request):
    if request.method == 'POST':
        user_name = request.POST.get('user_name')
        password = request.POST.get('password')
        user = User.objects.get(name=user_name)
        if user is None:
            raise User.DoesNotExist()
        else:
            pass
    else:
        return render(request, 'mpa/recoverpw.html')


def index(request):
    # return response.HttpResponse(u'次茶杯差别万磁王')
    return render(request, 'mpa/index.html')


def home(request):
    return render(request, 'mpa/home.html')


def demos(request, a, b):
    url = 'mpa/demo/' + a + '/' + b + '.html'
    return render(request, url)

rent_proj/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'rent/index.html')

learn/templates/learn/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <a href="/add/4/5/">计算 4+5</a>
</body>
</html>

mpa/templates/mpa/common/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <link rel="shortcut icon" href="{% static 'mpa/images/favicon_1.ico' %}">

    <title>{% block title %}Moltran - Responsive Admin Dashboard Template{% endblock %}</title>

    <link href="{% static 'mpa/plugins/sweetalert/dist/sweetalert.css' %}" rel="stylesheet" type="text/css">

    <link href="{% static 'mpa/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'mpa/css/core.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'mpa/css/icons.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'mpa/css/components.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'mpa/css/pages.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'mpa/css/menu.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'mpa/css/responsive.css' %}" rel="stylesheet" type="text/css">

    <script src="{% static 'mpa/js/modernizr.min.js' %}"></script>

    <!-- HTML5 Shim and Respond.js ' %} IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js ' %} doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js ' %}"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js ' %}/1.3.0/respond.min.js ' %}"></script>
    <![endif]-->
</head>
<body>
    {% include 'mpa/common/nav.html' %}

    {% block content %}
        <div>这里是默认内容，所有继承自这个模板的，如果不覆盖就显示这里的默认内容。</div>
    {% endblock %}

    {% include 'mpa/common/bottom.html' %}

    <!-- jQuery  -->
    <script src="{% static 'mpa/js/jquery.min.js' %}"></script>
    <script src="{% static 'mpa/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'mpa/js/detect.js' %}"></script>
    <script src="{% static 'mpa/js/fastclick.js' %}"></script>
    <script src="{% static 'mpa/js/jquery.blockUI.js' %}"></script>
    <script src="{% static 'mpa/js/waves.js' %}"></script>
    <script src="{% static 'mpa/js/wow.min.js' %}"></script>
    <script src="{% static 'mpa/js/jquery.nicescroll.js' %}"></script>
    <script src="{% static 'mpa/js/jquery.scrollTo.min.js' %}"></script>

    <script src="{% static 'mpa/js/RestAPIHelper.js' %}"></script>

    <!-- App js -->
    <script src="{% static 'mpa/js/jquery.app.js' %}"></script>

    {% block static %}

    {% endblock %}
</body>
</html>

mpa/templates/mpa/common/bottom.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!-- Footer -->
    <footer class="footer text-right">
        <div class="container">
            <div class="row">
                <div class="col-xs-6">
                    2018 © Sun.
                </div>
                <div class="col-xs-6">
                    <ul class="pull-right list-inline m-b-0">
                        <li>
                            <a href="#">About</a>
                        </li>
                        <li>
                            <a href="#">Help</a>
                        </li>
                        <li>
                            <a href="#">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <!-- End Footer -->
</body>
</html>

mpa/templates/mpa/demo/charts/chart-radial.html
{% extends 'mpa/common/base.html' %}
{% load static %}

{% block content %}
        <div class="wrapper">
            <div class="container">

                <!-- Page-Title -->
                <div class="row">
                    <div class="col-sm-12">
                        <div class="btn-group pull-right">
                            <button type="button" class="btn btn-primary dropdown-toggle waves-effect waves-light" data-toggle="dropdown" aria-expanded="false">Settings <span class="m-l-5"><i class="fa fa-cog"></i></span></button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                            </ul>
                        </div>
                        <h4 class="page-title">Radial charts </h4>
                    </div>
                </div>


                <!-- START row-->
                <div class="row">
                   <div class="col-lg-6">
                      <!-- START panel-->
                      <div class="panel panel-default">
                         <div class="panel-heading">Radial Size</div>
                         <div class="panel-body text-center">
                            <div class="row">
                               <div class="col-md-3">
                                  <div data-label="85%" class="radial-bar radial-bar-85 radial-bar-lg"></div>
                                  <p>
                                     <code>.radial-bar.radial-bar-85.radial-bar-lg</code>
                                  </p>
                               </div>
                               <div class="col-md-3">
                                  <div data-label="45%" class="radial-bar radial-bar-45"></div>
                               </div>
                               <div class="col-md-3">
                                  <div data-label="60%" class="radial-bar radial-bar-60 radial-bar-sm"></div>
                               </div>
                               <div class="col-md-3">
                                  <div data-label="20%" class="radial-bar radial-bar-20 radial-bar-xs"></div>
                               </div>
                            </div>
                         </div>
                      </div>
                      <!-- END panel-->
                      <!-- START panel-->
                      <div class="panel panel-default">
                         <div class="panel-heading">Radial with Images</div>
                         <div class="panel-body text-center">
                            <div class="row">
                               <div class="col-md-3">
                                  <div class="radial-bar radial-bar-20 radial-bar radial-bar-danger">
                                     <img src="{% static 'mpa/images/users/avatar-1.jpg' %}" alt="Image">
                                  </div>
                               </div>
                               <div class="col-md-3">
                                  <div data-label="35%" class="radial-bar radial-bar-35 radial-bar-warning">
                                     <img src="{% static 'mpa/images/users/avatar-2.jpg' %}" alt="Image">
                                  </div>
                               </div>
                               <div class="col-md-3">
                                  <div data-label="50%" class="radial-bar radial-bar-50 radial-bar-info">
                                     <img src="{% static 'mpa/images/users/avatar-3.jpg' %}" alt="Image">
                                  </div>
                               </div>
                               <div class="col-md-3">
                                  <div data-label="100%" class="radial-bar radial-bar-100 radial-bar-success">
                                     <img src="{% static 'mpa/images/users/avatar-4.jpg' %}" alt="Image">
                                  </div>
                               </div>
                            </div>
                         </div>
                      </div>
                      <!-- END panel-->
                      <!-- START panel-->
                      <div class="panel panel-default">
                         <div class="panel-heading">Radial with Tooltips</div>
                         <div class="panel-body text-center">
                            <div class="row">
                               <div class="col-md-3">
                                  <br>
                                  <div data-label="85%" data-toggle="tooltip" data-title="85%" class="radial-bar radial-bar-85"></div>
                               </div>
                               <div class="col-md-3">
                                  <br>
                                  <div data-label="45%" data-toggle="tooltip" data-title="45%" class="radial-bar radial-bar-45"></div>
                               </div>
                               <div class="col-md-3">
                                  <br>
                                  <div data-label="60%" data-toggle="tooltip" data-title="60%" class="radial-bar radial-bar-60"></div>
                               </div>
                               <div class="col-md-3">
                                  <br>
                                  <div data-label="20%" data-toggle="tooltip" data-title="20%" class="radial-bar radial-bar-20"></div>
                               </div>
                            </div>
                         </div>
                      </div>
                      <!-- END panel-->
                   </div>
                   <div class="col-lg-6">
                      <!-- START panel-->
                      <div class="panel panel-default">
                         <div class="panel-heading">Radial Variants</div>
                         <div class="panel-body text-center">
                            <div class="row">
                               <div class="col-md-3">
                                  <div data-label="20%" class="radial-bar radial-bar-20 radial-bar-lg radial-bar-danger"></div>
                                  <p>
                                     <code>.radial-bar.radial-bar-20.radial-bar-lg.radial-bar-danger</code>
                                  </p>
                               </div>
                               <div class="col-md-3">
                                  <div data-label="35%" class="radial-bar radial-bar-35 radial-bar-lg radial-bar-warning"></div>
                               </div>
                               <div class="col-md-3">
                                  <div data-label="50%" class="radial-bar radial-bar-50 radial-bar-lg radial-bar-info"></div>
                               </div>
                               <div class="col-md-3">
                                  <div data-label="100%" class="radial-bar radial-bar-100 radial-bar-lg radial-bar-success"></div>
                               </div>
                            </div>
                         </div>
                      </div>
                      <!-- END panel-->
                      <!-- START panel-->
                      <div class="panel panel-default">
                         <div class="panel-heading">Radial applications</div>
                         <div class="panel-body text-center">
                            <div data-label="85%" class="radial-bar radial-bar-85 radial-bar-lg"></div>
                            <p>Visitors</p>
                         </div>
                         <div class="panel-footer text-center">
                            <div class="row">
                               <div class="col-md-4">
                                  <div data-label="35%" class="radial-bar radial-bar-35 radial-bar-sm"></div>
                                  <p>
                                     <small>Conversions</small>
                                  </p>
                               </div>
                               <div class="col-md-4">
                                    <div data-label="45%" class="radial-bar radial-bar-45 radial-bar-sm"></div>
                                    <p>
                                        <small>Recurrent</small>
                                    </p>
                                </div>
                                <div class="col-md-4">
                                    <div data-label="20%" class="radial-bar radial-bar-20 radial-bar-sm"></div>
                                        <p>
                                            <small>Uniques</small>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- END panel-->
                    </div>
                </div>
                <!-- END row-->
            </div>
            <!-- end container -->

        </div>
        <!-- end wrapper -->
{% endblock %}

mpa/templates/mpa/demo/charts/chartjs.html
{% extends 'mpa/common/base.html' %}
{% load static %}

{% block content %}
        <div class="wrapper">
            <div class="container">

                <!-- Page-Title -->
                <div class="row">
                    <div class="col-sm-12">
                        <div class="btn-group pull-right">
                            <button type="button" class="btn btn-primary dropdown-toggle waves-effect waves-light" data-toggle="dropdown" aria-expanded="false">Settings <span class="m-l-5"><i class="fa fa-cog"></i></span></button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                            </ul>
                        </div>
                        <h4 class="page-title">Chartjs </h4>
                    </div>
                </div>


                <div class="row">
                    <div class="col-lg-6">
                        <div class="panel panel-border panel-primary">
                            <div class="panel-heading">
                                <h3 class="panel-title">Line Chart</h3>
                            </div>
                            <div class="panel-body">
                                <canvas id="lineChart" data-type="Line" width="520" height="250"></canvas>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-6">
                        <div class="panel panel-border panel-primary">
                            <div class="panel-heading">
                                <h3 class="panel-title">Bar chart</h3>
                            </div>
                            <div class="panel-body">
                                <canvas id="bar" data-type="Bar" height="250" width="800"></canvas>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-6">
                        <div class="panel panel-border panel-primary">
                            <div class="panel-heading">
                                <h3 class="panel-title">Pie chart</h3>
                            </div>
                            <div class="panel-body">
                                <canvas id="pie" data-type="Pie" height="300" width="800"></canvas>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-6">
                        <div class="panel panel-border panel-primary">
                            <div class="panel-heading">
                                <h3 class="panel-title">Radar chart</h3>
                            </div>
                            <div class="panel-body">
                                <canvas id="radar" data-type="Radar" width="300" height="300"></canvas>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="row">
                    <div class="col-lg-6">
                        <div class="panel panel-border panel-primary">
                            <div class="panel-heading">
                                <h3 class="panel-title">Donut chart</h3>
                            </div>
                            <div class="panel-body">
                                <canvas id="doughnut" data-type="Doughnut" height="250" width="800"></canvas>
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-6">
                        <div class="panel panel-border panel-primary">
                            <div class="panel-heading">
                                <h3 class="panel-title">Polar area chart</h3>
                            </div>
                            <div class="panel-body">
                                <canvas id="polarArea" data-type="PolarArea" width="300" height="250"> </canvas>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <!-- end container -->

        </div>
        <!-- end wrapper -->
{% endblock %}

{% block static %}

        <!-- Chart JS -->
        <script src="{% static 'mpa/plugins/Chart.js/Chart.min.js' %}"></script>
        <script src="{% static 'mpa/pages/chartjs.init.js' %}"></script>
{% endblock %}

mpa/templates/mpa/demo/charts/morris-chart.html
{% extends 'mpa/common/base.html' %}
{% load static %}

{% block content %}
        <div class="wrapper">
            <div class="container">

                <!-- Page-Title -->
                <div class="row">
                    <div class="col-sm-12">
                        <div class="btn-group pull-right">
                            <button type="button" class="btn btn-primary dropdown-toggle waves-effect waves-light" data-toggle="dropdown" aria-expanded="false">Settings <span class="m-l-5"><i class="fa fa-cog"></i></span></button>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something else here</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                            </ul>
                        </div>
                        <h4 class="page-title">Morris Chart </h4>
                    </div>
                </div>


                <div class="row">
                    <!-- BAR Chart -->
                    <div class="col-lg-6">
                        <div class="panel panel-border panel-primary">
                            <div class="panel-heading">
                                <h3 class="panel-title">Bar Chart   </h3>
                            </div>
                            <div class="panel-body">
                                <div id="morris-bar-example" style="height: 300px"></div>
                            </div>
                        </div>
                    </div> <!-- col -->

                    <!--  Line Chart -->
                    <div class="col-lg-6">
                        <div class="panel panel-border panel-primary">
                            <div class="panel-heading">
                                <h3 class="panel-title">Line Chart</h3>
                            </div>
                            <div class="panel-body">
                                <div id="morris-line-example" style="height: 300px"></div>
                            </div>
                        </div>
                    </div> <!-- col -->
                </div> <!-- End row-->


                <div class="row">

                    <!-- Area Chart -->
                    <div class="col-lg-6">
                        <div class="panel panel-border panel-primary">
                            <div class="panel-heading">
                                <h3 class="panel-title">Area Chart</h3>
                            </div>
                            <div class="panel-body">
                                <div id="morris-area-example" style="height: 300px"></div>
                            </div>
                        </div>
                    </div> <!-- col -->


                    <!-- Donut Chart -->
                    <div class="col-lg-6">
                        <div class="panel panel-border panel-primary">
                            <div class="panel-heading">
                                <h3 class="panel-title">Donut Chart</h3>
                            </div>
                            <div class="panel-body">
                                <div id="morris-donut-example" style="height: 300px"></div>
                            </div>
                        </div>
                    </div> <!-- col -->
                </div> <!-- End row-->
            </div>
            <!-- end container -->

        </div>
        <!-- end wrapper -->
{% endblock %}

{% block static %}
        <!--Morris Chart-->
        <script src="{% static 'mpa/plugins/morris.js/morris.min.js' %}"></script>
        <script src="{% static 'mpa/plugins/raphael/raphael-min.js' %}"></script>
        <script src="{% static 'mpa/pages/morris.init.js' %}"></script>

{% endblock %}

mpa/templates/mpa/login.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
        <meta name="author" content="Coderthemes">

        <link rel="shortcut icon" href="{% static 'mpa/images/favicon_1.ico">

        <title>Moltran - Responsive Admin Dashboard Template</title>

        <link href="{% static 'mpa/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'mpa/css/core.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'mpa/css/icons.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'mpa/css/components.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'mpa/css/pages.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'mpa/css/menu.css' %}" rel="stylesheet" type="text/css">
        <link href="{% static 'mpa/css/responsive.css' %}" rel="stylesheet" type="text/css">

        <script src="{% static 'mpa/js/modernizr.min.js' %}"></script>
<script>
  
 
 
 

 
  

</script>

        <!-- HTML5 Shim and Respond.js' %} IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js' %} doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js' %}"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js' %}/1.3.0/respond.min.js' %}"></script>
        <![endif]-->

        
    </head>
    <body>
        <div class="wrapper-page">
            <div class="panel panel-color panel-primary panel-pages">
                <div class="panel-heading">
                    <h3 class="text-center m-t-10 text-white"> 登录 <strong>MPA</strong> </h3>
                </div> 

                <div class="panel-body">
                <form class="form-horizontal m-t-20" action="{% url 'mpa:login' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="col-xs-12">
                            <input name="user_name" class="form-control input-lg" type="text" required="" placeholder="用户名">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-xs-12">
                            <input name="password" class="form-control input-lg" type="password" required="" placeholder="密码">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-xs-12">
                            <div class="checkbox checkbox-primary">
                                <input name="remember_me" id="checkbox-signup" type="checkbox">
                                <label for="checkbox-signup">
                                    记住我
                                </label>
                            </div>
                        </div>
                    </div>
                    
                    <div class="form-group text-center m-t-40">
                        <div class="col-xs-12">
                            <button class="btn btn-primary btn-lg w-lg waves-effect waves-light" type="submit">登录</button>
                        </div>
                    </div>

                    <div class="form-group m-t-30">
                        <div class="col-sm-7">
                            <a href="/mpa/to_reset_pw"><i class="fa fa-lock m-r-5"></i> 忘记密码?</a>
                        </div>
                        <div class="col-sm-5 text-right">
                            <a href="/mpa/to_register">创建账户</a>
                        </div>
                    </div>
                </form> 
                </div>                                 
            </div>
        </div>

        
    	<script>
            var resizefunc = [];
        </script>

        <!-- Main  -->
        <script src="{% static 'mpa/js/jquery.min.js' %}"></script>
        <script src="{% static 'mpa/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'mpa/js/detect.js' %}"></script>
        <script src="{% static 'mpa/js/fastclick.js' %}"></script>
        <script src="{% static 'mpa/js/jquery.slimscroll.js' %}"></script>
        <script src="{% static 'mpa/js/jquery.blockUI.js' %}"></script>
        <script src="{% static 'mpa/js/waves.js' %}"></script>
        <script src="{% static 'mpa/js/wow.min.js' %}"></script>
        <script src="{% static 'mpa/js/jquery.nicescroll.js' %}"></script>
        <script src="{% static 'mpa/js/jquery.scrollTo.min.js' %}"></script>

        <script src="{% static 'mpa/js/jquery.app.js' %}"></script>
	
	</body>
</html>